# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-12-30 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20201228_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_it',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
    ]
