# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-12-30 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_post_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_it',
            name='answer',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post_it',
            name='description',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post_it',
            name='question',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post_it',
            name='user_email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_it',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
